name: Run PHPStans

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    run_phpstans:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    # all jobs must fail, to show PHPStan finds the errors as expected
                    -
                        name: 'PHPStan Unused Public'
                        run: vendor/bin/phpstan analyse --configuration phpstan-unused-public.neon

                    -
                        name: 'PHPStan Cognitive Complexity'
                        run: vendor/bin/phpstan analyse --configuration phpstan-cognitive-complexity.neon

                    -
                        name: 'PHPStan Type Coverage'
                        run: vendor/bin/phpstan analyse --configuration phpstan-type-coverage.neon

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            -   run: ${{ matrix.actions.run }}
